<a href="https://colab.research.google.com/github/rabinkahoonay/test/blob/main/project_capital_markets_23_3_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip install yfinance --upgrade --no-cache-dir
#!pip install yahoo_fin
import pandas as pd
import yfinance as yf
from datetime import date
from datetime import datetime, timedelta

index_list = ['^GSPC', '^TA125.TA', '^DJI', '^IXIC', '^VIX']
data = yf.download(index_list,'1980-1-1')['Adj Close']
#pd=pd.set_option('display.max_columns', None)
df= pd.DataFrame([[data]])
df=data.fillna(method='ffill')
df = df.reset_index().round(2)
df = df.rename(columns={'^GSPC':'S&P500'    ,'^TA125.TA':'TA_125',
                          '^DJI' :'Dow_Jones' ,'^IXIC'    :'NASDAQ',
                          '^VIX' :'VIX'       })
# limit to 2 digits after the decimal point
#daily_data=df.round(2)
# print ("Daily Data of the indices \n   " , daily_data)
# print ("datetime.date" , datetime.date)
df['Day'] = pd.to_datetime(df['Date']).dt.day
df['Month'] = pd.to_datetime(df['Date']).dt.month
df['Year'] = pd.to_datetime(df['Date']).dt.year
df = df.set_index('Date')

[*********************100%%**********************]  5 of 5 completed

In [ ]:
def add_daily_change(df):
  # Identify time series columns (assuming numeric datatypes for simplicity)
  numeric_cols = [col for col in df.columns if pd.api.types.is_numeric_dtype(df[col])]
  timeseries_cols = [col for col in numeric_cols if len(df) > 1]  # Ensure there are at least 2 rows

  # Create new columns with daily changes (shift by -1 for difference)
  for col in timeseries_cols:
    df[col + "_p"] = df[col].diff(periods=1).round(2)
    df[col + "_c1"]= (df[col].pct_change(1)*100).round(2)
    df[col + "_c2"]= (df[col].pct_change(2)*100).round(2)
    df[col + "_c3"]= (df[col].pct_change(3)*100).round(2)
  return df



df = add_daily_change(df.copy())  # Operate on a copy to avoid modifying the original
df=df.round(2)
print("Daily Data of the indices \n   " , df.tail(5))
df.tail(5)

Daily Data of the indices
    Ticker      Dow_Jones   S&P500    NASDAQ   TA_125    VIX  Day  Month  Year  \
Date
2024-03-18   38790.43  5149.42  16103.45  1966.02  14.33   18      3  2024
2024-03-19   39110.76  5178.51  16166.79  1980.44  13.82   19      3  2024
2024-03-20   39512.13  5224.62  16369.41  2003.08  13.04   20      3  2024
2024-03-21   39781.37  5241.53  16401.84  2023.79  12.92   21      3  2024
2024-03-22   39475.90  5234.18  16428.82  2023.79  13.06   22      3  2024

Ticker      Dow_Jones_p  Dow_Jones_c1  Dow_Jones_c2  Dow_Jones_c3  S&P500_p  \
Date
2024-03-18        75.66          0.20          0.20         -0.30     32.33
2024-03-19       320.33          0.83          1.02          1.02     29.09
2024-03-20       401.37          1.03          1.86          2.06     46.11
2024-03-21       269.24          0.68          1.71          2.55     16.91
2024-03-22      -305.47         -0.77         -0.09          0.93     -7.35

Ticker      S&P500_c1  S&P500_c2  S&P500_c3  NASDAQ_p  NASDAQ_c1  NASDAQ_c2  \
Date
2024-03-18       0.63       0.63      -0.02    130.28       0.82       0.82
2024-03-19       0.56       1.20       1.20     63.34       0.39       1.21
2024-03-20       0.89       1.46       2.10    202.62       1.25       1.65
2024-03-21       0.32       1.22       1.79     32.43       0.20       1.45
2024-03-22      -0.14       0.18       1.08     26.98       0.16       0.36

Ticker      NASDAQ_c3  TA_125_p  TA_125_c1  TA_125_c2  TA_125_c3  VIX_p  \
Date
2024-03-18      -0.16     19.62       1.01       2.52       2.52  -0.08
2024-03-19       1.21     14.42       0.73       1.75       3.27  -0.51
2024-03-20       2.48     22.64       1.14       1.89       2.91  -0.78
2024-03-21       1.85     20.71       1.03       2.19       2.94  -0.12
2024-03-22       1.62      0.00       0.00       1.03       2.19   0.14

Ticker      VIX_c1  VIX_c2  VIX_c3  Day_p  Day_c1  Day_c2  Day_c3  Month_p  \
Date
2024-03-18   -0.56   -0.56   -0.49    1.0    5.88   20.00   28.57      0.0
2024-03-19   -3.56   -4.09   -4.09    1.0    5.56   11.76   26.67      0.0
2024-03-20   -5.64   -9.00   -9.51    1.0    5.26   11.11   17.65      0.0
2024-03-21   -0.92   -6.51   -9.84    1.0    5.00   10.53   16.67      0.0
2024-03-22    1.08    0.15   -5.50    1.0    4.76   10.00   15.79      0.0

Ticker      Month_c1  Month_c2  Month_c3  Year_p  Year_c1  Year_c2  Year_c3
Date
2024-03-18       0.0       0.0       0.0     0.0      0.0      0.0      0.0
2024-03-19       0.0       0.0       0.0     0.0      0.0      0.0      0.0
2024-03-20       0.0       0.0       0.0     0.0      0.0      0.0      0.0
2024-03-21       0.0       0.0       0.0     0.0      0.0      0.0      0.0
2024-03-22       0.0       0.0       0.0     0.0      0.0      0.0      0.0

Ticker,Dow_Jones,S&P500,NASDAQ,TA_125,VIX,Day,Month,Year,Dow_Jones_p,Dow_Jones_c1,Dow_Jones_c2,Dow_Jones_c3,S&P500_p,S&P500_c1,S&P500_c2,S&P500_c3,NASDAQ_p,NASDAQ_c1,NASDAQ_c2,NASDAQ_c3,TA_125_p,TA_125_c1,TA_125_c2,TA_125_c3,VIX_p,VIX_c1,VIX_c2,VIX_c3,Day_p,Day_c1,Day_c2,Day_c3,Month_p,Month_c1,Month_c2,Month_c3,Year_p,Year_c1,Year_c2,Year_c3
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2024-03-18,38790.43,5149.42,16103.45,1966.02,14.33,18,3,2024,75.66,0.20,0.20,-0.30,32.33,0.63,0.63,-0.02,130.28,0.82,0.82,-0.16,19.62,1.01,2.52,2.52,-0.08,-0.56,-0.56,-0.49,1.0,5.88,20.00,28.57,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-03-19,39110.76,5178.51,16166.79,1980.44,13.82,19,3,2024,320.33,0.83,1.02,1.02,29.09,0.56,1.20,1.20,63.34,0.39,1.21,1.21,14.42,0.73,1.75,3.27,-0.51,-3.56,-4.09,-4.09,1.0,5.56,11.76,26.67,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-03-20,39512.13,5224.62,16369.41,2003.08,13.04,20,3,2024,401.37,1.03,1.86,2.06,46.11,0.89,1.46,2.10,202.62,1.25,1.65,2.48,22.64,1.14,1.89,2.91,-0.78,-5.64,-9.00,-9.51,1.0,5.26,11.11,17.65,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-03-21,39781.37,5241.53,16401.84,2023.79,12.92,21,3,2024,269.24,0.68,1.71,2.55,16.91,0.32,1.22,1.79,32.43,0.20,1.45,1.85,20.71,1.03,2.19,2.94,-0.12,-0.92,-6.51,-9.84,1.0,5.00,10.53,16.67,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-03-22,39475.90,5234.18,16428.82,2023.79,13.06,22,3,2024,-305.47,-0.77,-0.09,0.93,-7.35,-0.14,0.18,1.08,26.98,0.16,0.36,1.62,0.00,0.00,1.03,2.19,0.14,1.08,0.15,-5.50,1.0,4.76,10.00,15.79,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#df_m = df[df['Month_p'] == 1]
#df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')
#df_m=df.loc[df['Date'].dt.day == df['Date'].dt.monthrange()[1]]
#df_m = df.loc[df.index.day == df.index.monthrange()[1]]
#df_m = df.loc[df.index.to_datetime().day == df.index.to_datetime().monthrange()[1]]
# for idx in df.index:
#   if idx.day == monthrange(idx.year, idx.month)[1]:
#     df_m = df_m.append(df.loc[idx])
# print (df_m)
for idx in df.index:
  if idx.day == monthrange(idx.year, idx.month)[1]:
    # Use concat to append the row to df_m
    df_m = pd.concat([df_m, df.loc[idx]], ignore_index=True)

# Print result
print(df_m)

       col1  Dow_Jones  S&P500  NASDAQ  TA_125  VIX   Day  Month    Year  \
0      20.0        NaN     NaN     NaN     NaN  NaN   NaN    NaN     NaN
1       NaN        NaN  114.16  161.75     NaN  NaN  31.0    1.0  1980.0
2       NaN        NaN  113.66  158.03     NaN  NaN  29.0    2.0  1980.0
3       NaN        NaN  102.09  131.00     NaN  NaN  31.0    3.0  1980.0
4       NaN        NaN  106.29  139.99     NaN  NaN  30.0    4.0  1980.0
...     ...        ...     ...     ...     ...  ...   ...    ...     ...
31505   NaN        NaN     NaN     NaN     NaN  NaN   NaN    NaN     NaN
31506   NaN        NaN     NaN     NaN     NaN  NaN   NaN    NaN     NaN
31507   NaN        NaN     NaN     NaN     NaN  NaN   NaN    NaN     NaN
31508   NaN        NaN     NaN     NaN     NaN  NaN   NaN    NaN     NaN
31509   NaN        NaN     NaN     NaN     NaN  NaN   NaN    NaN     NaN

       Dow_Jones_p  Dow_Jones_c1  Dow_Jones_c2  Dow_Jones_c3  S&P500_p  \
0              NaN           NaN           NaN           NaN       NaN
1              NaN           NaN           NaN           NaN     -1.04
2              NaN           NaN           NaN           NaN      1.31
3              NaN           NaN           NaN           NaN      1.41
4              NaN           NaN           NaN           NaN      0.43
...            ...           ...           ...           ...       ...
31505          NaN           NaN           NaN           NaN       NaN
31506          NaN           NaN           NaN           NaN       NaN
31507          NaN           NaN           NaN           NaN       NaN
31508          NaN           NaN           NaN           NaN       NaN
31509          NaN           NaN           NaN           NaN       NaN

       S&P500_c1  S&P500_c2  S&P500_c3  NASDAQ_p  NASDAQ_c1  NASDAQ_c2  \
0            NaN        NaN        NaN       NaN        NaN        NaN
1          -0.90       0.08      -0.60      0.45       0.28       0.91
2           1.17       1.14      -0.28      0.57       0.36       0.19
3           1.40       3.94       3.46      1.75       1.35       5.57
4           0.41       0.62       1.07      0.64       0.46       1.05
...          ...        ...        ...       ...        ...        ...
31505        NaN        NaN        NaN       NaN        NaN        NaN
31506        NaN        NaN        NaN       NaN        NaN        NaN
31507        NaN        NaN        NaN       NaN        NaN        NaN
31508        NaN        NaN        NaN       NaN        NaN        NaN
31509        NaN        NaN        NaN       NaN        NaN        NaN

       NASDAQ_c3  TA_125_p  TA_125_c1  TA_125_c2  TA_125_c3  VIX_p  VIX_c1  \
0            NaN       NaN        NaN        NaN        NaN    NaN     NaN
1           0.65       NaN        NaN        NaN        NaN    NaN     NaN
2          -0.30       NaN        NaN        NaN        NaN    NaN     NaN
3          -0.92       NaN        NaN        NaN        NaN    NaN     NaN
4           1.50       NaN        NaN        NaN        NaN    NaN     NaN
...          ...       ...        ...        ...        ...    ...     ...
31505        NaN       NaN        NaN        NaN        NaN    NaN     NaN
31506        NaN       NaN        NaN        NaN        NaN    NaN     NaN
31507        NaN       NaN        NaN        NaN        NaN    NaN     NaN
31508        NaN       NaN        NaN        NaN        NaN    NaN     NaN
31509        NaN       NaN        NaN        NaN        NaN    NaN     NaN

       VIX_c2  VIX_c3  Day_p  Day_c1  Day_c2  Day_c3  Month_p  Month_c1  \
0         NaN     NaN    NaN     NaN     NaN     NaN      NaN       NaN
1         NaN     NaN    1.0    3.33    6.90   10.71      0.0       0.0
2         NaN     NaN    1.0    3.57    7.41   11.54      0.0       0.0
3         NaN     NaN    3.0   10.71   14.81   19.23      0.0       0.0
4         NaN     NaN    1.0    3.45    7.14   20.00      0.0       0.0
...       ...     ...    ...     ...     ...     ...      ...       ...
31505     NaN     NaN    NaN     NaN     NaN     NaN      NaN       NaN
31506     NaN     NaN    NaN     NaN     NaN     NaN      NaN       NaN
31507     NaN     NaN    NaN     NaN     NaN     NaN      NaN       NaN
31508     NaN     NaN    NaN     NaN     NaN     NaN      NaN       NaN
31509     NaN     NaN    NaN     NaN     NaN     NaN      NaN       NaN

       Month_c2  Month_c3  Year_p  Year_c1  Year_c2  Year_c3    0
0           NaN       NaN     NaN      NaN      NaN      NaN  NaN
1           0.0       0.0     0.0      0.0      0.0      0.0  NaN
2           0.0       0.0     0.0      0.0      0.0      0.0  NaN
3           0.0       0.0     0.0      0.0      0.0      0.0  NaN
4           0.0       0.0     0.0      0.0      0.0      0.0  NaN
...         ...       ...     ...      ...      ...      ...  ...
31505       NaN       NaN     NaN      NaN      NaN      NaN  0.0
31506       NaN       NaN     NaN      NaN      NaN      NaN  0.0
31507       NaN       NaN     NaN      NaN      NaN      NaN  0.0
31508       NaN       NaN     NaN      NaN      NaN      NaN  0.0
31509       NaN       NaN     NaN      NaN      NaN      NaN  0.0

[31510 rows x 42 columns]

In [ ]:
data = {'Date': ['2024-03-18', '2024-03-31', '2024-04-01'], 'col1': [10, 20, 30]}
df = pd.DataFrame(data)

# Set 'Date' as datetime index (assuming it's a string column)
df['Date'] = pd.to_datetime(df['Date'])  # Convert string dates to datetime
df.set_index('Date', inplace=True)

# Sort dates in ascending order
df = df.sort_index()

# Create empty DataFrame for end-of-month rows
df_m = pd.DataFrame()

# Loop through index and check for end of month
for idx in df.index:
  if idx.day == monthrange(idx.year, idx.month)[1]:
    df_m = df_m.append(df.loc[idx])

# Print result
print(df_m)

            col1
2024-03-31    20

<ipython-input-60-30a288aa41e9>:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_m = df_m.append(df.loc[idx])

In [ ]:
data = {'Date': ['2024-03-18', '2024-03-31', '2024-04-01'], 'col1': [10, 20, 30]}
df = pd.DataFrame(data)

# Set time as index (assuming 'Date' is your datetime column)
df.set_index('Date', inplace=True)

# Sort dates in ascending order
df = df.sort_index()

# Create empty DataFrame for end-of-month rows
df_m = pd.DataFrame()

# Loop through index and check for end of month
for idx in df.index:
  if idx.day == monthrange(idx.year, idx.month)[1]:
    df_m = df_m.append(df.loc[idx])

# Print result
print(df_m)

AttributeError: 'str' object has no attribute 'day'

In [ ]:
def is_end_of_month(dt):
    return dt.day == dt.monthrange()[1]

df_m = df.loc[df.index.apply(is_end_of_month)]

In [ ]:
import pandas as pd
from calendar import monthrange

data = {'Date': ['2024-03-18', '2024-03-31', '2024-04-01'], 'col1': [10, 20, 30]}
df = pd.DataFrame(data)

# Set time as index
df.set_index('Date', inplace=True)

# Sort dates in ascending order
df = df.sort_index()

# Extract day and monthrange for each index element
day = df.index.day
month_range = df.index.to_period('M').dt.monthrange()[1]  # Use to_period for monthrange

# Select rows where day equals last day of month
df_m = df.loc[day == month_range]

# Print result
print(df_m)

In [ ]:
daily_data['Month'] = pd.to_datetime(daily_data['Date']).dt.month
daily_data['Day'] = pd.to_datetime(daily_data['Date']).dt.day
daily_data['Year'] = pd.to_datetime(daily_data['Date']).dt.year
print (daily_data.tail(5))

In [ ]:
# daily_changes=daily_data.drop(columns=['Month', 'Day','Year'])
# print (daily_changes.tail(20))

In [ ]:
# type (daily_changes)
# print (daily_changes.dtypes)

In [ ]:
daily_changes=daily_changes.set_index('Date')
daily_changes = (daily_changes.pct_change()*100).round(2)
print ("DATA4   \n  "  , "Daily Percent Changes of the indices  \n   "   ,  daily_changes.tail(20))

In [ ]:
daily_changes = daily_changes.reset_index()
print (daily_changes.tail(20))
#del daily_changes['index']


daily_changes['Date']=daily_changes['Date']
daily_changes['Month'] = pd.to_datetime(daily_data['Date']).dt.month
daily_changes['Day'] = pd.to_datetime(daily_data['Date']).dt.day
daily_changes['Year'] = pd.to_datetime(daily_data['Date']).dt.year
print (daily_changes.tail(20))

In [ ]:
type (daily_changes)
print (daily_changes.dtypes)

In [ ]:
monthly_index = pd.DataFrame(pd.date_range(start='1980-1-1',end='2050-1-1',freq='M'),
                                                         columns=['Date'])
daily_index = pd.DataFrame(pd.date_range(start='1980-1-1',end='2050-1-1',freq='D'),
                                                         columns=['Date'])
print(monthly_index)
print(daily_index)

# #end_of_month = end_of_month.reset_index()
# #yearly_index=pd.date_range(start='1980-1-1',end='2050-1-1',freq='Y')
# #print(yearly_index)
# monthly_index= pd.DataFrame([[end_of_month]])
# type (monthly_index)
# print(monthly_index.tail(20))
# monthly_index['last_day_of_month']=1
# type (monthly_index)
# print(monthly_index.tail(20))

In [ ]:
monthly_data = daily_index.merge(daily_data, on='Date', how='left')
print (monthly_data.loc(0-20,0-3))
monthly_data=monthly_data.fillna(method='ffill')
print (monthly_data.loc(0-20,0-3))

In [ ]:
monthly_data = monthly_index.merge(daily_data, left_on='Date', right_on='Date')
print (monthly_data.head(35))